### ISSUE TITLE
Correctly handle most-negative integer

### ISSUE THREAD

**Issue by kpu** [miloyip/itoa-benchmark#8]
This function depends on undefined behavior for std::numeric_limits<int32_t>::min():

void i32toa_sse2(int32_t value, char* buffer) {
if (value < 0) {
*buffer++ = '-';
value = -value;
}
u32toa_sse2(static_cast<uint32_t>(value), buffer);
}

value = -std::numeric_limits<int32_t>::min() is not defined in C++:
http://stackoverflow.com/questions/16188263/is-signed-integer-overflow-still-undefined-behavior-in-c

I've observed g++ 4.9.1 create code that segfaults: it incorrectly enters the if (v < 10000) branch then tries to lookup gDigitsLut[d1] because d1 is too big.  

Recommend:
void i32toa_sse2(int32_t value, char* buffer) {
if (value < 0) {
*buffer++ = '-';
u32toa_sse2(~static_cast<uint32_t>(value) + 1, buffer);
} else {
u32toa_sse2(static_cast<uint32_t>(value), buffer);
}
}
Same for 64.

**Comment by miloyip** [comment]
Thank you for your information.
However I have not verified with the compiler you mentioned.
Can you help me to verify whether this is fixed properly?
Thank you.

**Comment by kpu** [comment]
It now works and produces the correct result, thanks.
